### ISSUE TITLE
Maven 3.2.5 with JDK 6u45, not able to find smart builder

### ISSUE THREAD

**Issue by galegofer** [takari/takari-smart-builder#10]
Using JDK 1.6.45
Maven 3.2.5
takari-smart-builder-0.6.1 (Tried with 0.4.0 and 0.4.1 also) at $M2_HOME/lib/ext

Using command:  mvn clean package -Pall --builder smart -T1.0C for multimodule project.

Maven is displaying the next:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.601 s (Wall Clock)
[INFO] Finished at: 2017-09-28T09:35:46+02:00
[INFO] Final Memory: 12M/527M
[INFO] ------------------------------------------------------------------------
[ERROR] The builder requested using id = smart cannot be found -> [Help 1]

In theory, and according to the Takari book, it should be compatible with Maven 3.2.1, is this a bug or I may be missing something there?.

**Comment by galegofer** [comment]
I dont thing is related to https://github.com/takari/takari-smart-builder/issues/2.

**Comment by galegofer** [comment]
I tried running it with JDK8u101 and Maven 3.2.5 and seems to be working.

**Comment by ifedorenko** [comment]
Maven 3.2.5 should work, but Java 6 is not supported, you need java 8. If you need older java support, feel free to fork this repository (it's EPL) and make the necessary changes.
