### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by laeubi** [takari/takari-smart-builder#15]
It seems there are two PRs open for quite a long time:

- https://github.com/takari/takari-smart-builder/pull/14
- https://github.com/takari/takari-smart-builder/pull/12

As I plan to eventually use and enhance this for a different use-case I wonder if the project is still maintained and contributions are possible, or if one should fork it instead.

**Comment by laeubi** [comment]
FYI @ifedorenko @jvanzyl

**Comment by cstamas** [comment]
It is, just not getting with time...

**Comment by laeubi** [comment]
@cstamas that sounds promising, but what does this mean in details?

e.g. will there be at least time to review/merge PRs an make releases?

**Comment by cstamas** [comment]
First I want to dust them off, already happened with parent pom, testing framework, lifecycle. Currently am looking at io.takari.incremental and will get here as well....

So probably yes.

**Comment by laeubi** [comment]
Probably one can start with this
- https://github.com/takari/takari-smart-builder/pull/16

to see if it builds or what probably needs to be done...

**Comment by laeubi** [comment]
Another easy one:
- https://github.com/takari/takari-smart-builder/pull/17

**Comment by laeubi** [comment]
@gnodet seem to use [a fork of this project](https://github.com/apache/maven-mvnd/blob/master/daemon/src/main/java/org/mvndaemon/mvnd/builder/SmartBuilder.java) in [mvnd](https://github.com/apache/maven-mvnd) so probably it would be worth to bring any improvement here back to this repos so code can be shared instead of copied.

**Comment by gnodet** [comment]
Done
