### ISSUE TITLE
Do not clone the session when using maven >= 3.9.x

### ISSUE THREAD

**Issue by gnodet** [takari/takari-smart-builder#24]
See https://github.com/apache/maven-mvnd/issues/841#issuecomment-1537244819

**Comment by gnodet** [comment]
Not an issue with the builder.

**Comment by gnodet** [comment]
This is actually an issue in the builder.

**Comment by ppalaga** [comment]
Why does Maven 3.9.0+ make a difference?

**Comment by cstamas** [comment]
mvnd by default uses smart builder, while 3.9.x does not (only if configured as extension). That would be an interesting case to test: 3.9.x w/ smart builder extension and builder config to use it actually.

**Comment by cstamas** [comment]
@gnodet ...or did I miss the point? I just now see that I misinterpreted @ppalaga question.... So yes, why does Maven 3.9.0+ makes a difference?

**Comment by gnodet** [comment]
> @gnodet ...or did I miss the point? I just now see that I misinterpreted @ppalaga question.... So yes, why does Maven 3.9.0+ makes a difference?

Because the session cloning has been removed in 3.9.x with https://github.com/apache/maven/pull/743
