### ISSUE TITLE
Not compatible with SonarQube plugin

### ISSUE THREAD

**Issue by henryju** [takari/takari-smart-builder#3]
Hi guys,

One of our user reported he can't use takari smart builder + SonarQube Maven plugin (sonar:sonar). This goal is supposed to be an aggregator so only executed on root project but with smart builder it seems to be executed on each module.

See the original report (with a reproducer):
https://groups.google.com/d/msg/sonarqube/3HApUrDEnyE/ApWZciGRBgAJ

For me this is an issue of smart builder but please tell me if I'm wrong or if there is something we can do on our side to improve compatibility.

**Comment by ifedorenko** [comment]
Pushed proposed fix to `aggregator-mojo` branch. Still need to figure out sensible way to report build metrics and how to deal with persistent timings when using aggregator mojos.
