### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by andrewgdavis** [takari/takari-smart-builder#4]
sorry for cross post-- but the issue seems to belong here.

https://github.com/takari/takari-local-repository/issues/6

I took a quick look at the code and the relevant piece seems to be here:

https://github.com/takari/takari-smart-builder/blob/master/src/main/java/io/takari/maven/builder/smart/SmartBuilderImpl.java:169
```
    } catch (ExecutionException e) {
        // we get here when unhandled exception or error occurred on the worker thread
        // this can be low-level system problem, like OOME, or runtime exception in maven code
        // there is no meaningful recovery, so we shutdown and rethrow the exception
        shutdown();
        throw e;
      }
```

Any ideas on how to deal with the underlying low-level system problems?

**Comment by ifedorenko** [comment]
No, this is not an issue with the smart builder. If the build fails fails for whatever reason, the smart builder must propagate the error message to the user, but can't do much beyond that.
