### ISSUE TITLE
Example maven.config doesn't work for Apache Maven 3.9.6

### ISSUE THREAD

**Issue by kimholan** [takari/takari-smart-builder#43]
I couldn't get the maven.config working with Apache Maven 3.9.6 using the example config from the README.MD:

```
-b smart
-T2C
```

The example maven.config gives me the following error:
```
[ERROR] The builder requested using id =  smart cannot be found -> [Help 1]
```
 
For 3.9.6 apparently '-b smart' are two arguments and needs to be split over multiple lines:

```
-b
smart
-T0.5C
```

This will make the build use the extension as described.

**Comment by cstamas** [comment]
Thanks, fixed
