### ISSUE TITLE
Please add license text

### ISSUE THREAD

**Issue by definite** [takari/takari-smart-builder#7]
I would like to know the license for this project. By looking other projects under takari, it looks Apache License v2 is used. Is that also apply to the takari-smart-builder?

Please also put a License file in the repository, it will be great help for packagers to redistribute under the correct license.

**Comment by ifedorenko** [comment]
@jvanzyl do you have a preference between EPL and Apache?

**Comment by jvanzyl** [comment]
For Maven-related work ASL 2.0 is more appropriate.

**Comment by ifedorenko** [comment]
Added ASL v2 license file and pom.xml `<license>` element. 

If anyone cares enough about licenses to fix license headers in all sources, please open a pull request with license-maven-plugin configuration and I'll review and apply it.

**Comment by definite** [comment]
Thanks for providing the LICENSE file.
